#공통 설정
server:
  tomcat:
    uri-encoding: utf-8

#jpa setting
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

---
#profiles
spring:
  redis:
    host: 127.0.0.1
    port: 6379

  config:
    activate:
      on-profile: "testDB"
  datasource:
    url: jdbc:h2:file:C:/data/testDB
    username: sa
    password:

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: "EC2"

  datasource:
    url: jdbc:h2:file:/home/ubuntu/data/testDB
    username: sa
    password:
---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: "SUB"

  datasource:
    url: jdbc:h2:file:/home/ubuntu/data/testDB
    username: sa
    password:
---
#jwt
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

client:
  id: 0e44958bb185436290f9
  secret: 15f403a8e8de9157781aeedeb375acd7f60385a9
---
#swagger setting
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher


---
#freemarker
spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
---
#logging
logging:
  file:
    path: ./log
---
#Spring admin
management:
  endpoints:
    web:
      exposure:
        include: "*"